FROM gcc:11.5-bullseye AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake \
    libpq-dev \
    postgresql-server-dev-13 \
    libssl-dev \
    ca-certificates \
    libasio-dev \
    binutils \
    && rm -rf /var/lib/apt/lists/* \
    && cmake --version

WORKDIR /build

COPY . .

# Сборка только тестов
RUN cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS=ON \
    && cmake --build build --target empl_back_tests -j$(nproc)

# Runtime для тестов
FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq5 \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build

# Копируем только собранный бинарник тестов
COPY --from=builder /build/build/empl_back_tests /build/

ENV SERVER_HOST=localhost
ENV SERVER_PORT=8080

# Запускаем тесты напрямую
CMD ["/build/empl_back_tests", "--gtest_color=yes", "--gtest_brief=1"]